### ISSUE TITLE
Cannot compile against hdr_histogram_log.h

### ISSUE THREAD

**Issue by beberlei** [HdrHistogram/HdrHistogram_c#26]
The `hdr_time.h` is not exported, but its required by `hdr_histogram_log.h`. 

getting:

    /usr/local/include/hdr/hdr_histogram_log.h:28:22: fatal error: hdr_time.h: No such file or directory
     #include "hdr_time.h"

This error was recently introduced in dfac123f

**Comment by mikeb01** [comment]
Pull request applied.  Thanks.
